### ISSUE TITLE
getcelldata returning zero data

### ISSUE THREAD

**Issue by fguilhaumon** [ropensci/seaaroundus#6]
Hi there,

I'm trying the 'getcelldata' for a research project and, running the example, I'm unable to get any data :

cells <- getcells("POLYGON ((-48.177685950413291 15.842380165289299,-48.177685950413291 15.842380165289299,
-54.964876033057919 28.964280991735578,-35.960743801652967 27.606842975206646,-48.177685950413291 
15.842380165289299))")
# get datagrid of cell data for a given year and list of cells

d <- getcelldata(2005, cells)
# looking at the results

d
_> data frame with 0 columns and 0 rows_

if this help here is the result of the 'POST' call in the 'postapi' function :

resp <- POST(url, body=body, add_headers("X-Request-Source" = "r"))

> resp
> Response [http://api.seaaroundus.org/api/v1/spatial/r/cells]
>   Date: 2016-09-21 12:51
>   Status: 200
>   Content-Type: application/json
>   Size: **130 B**

Here is my sessioninfo() :

R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C  
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8  
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8  
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C  
 [9] LC_ADDRESS=C               LC_TELEPHONE=C  
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] jsonlite_1.1      httr_1.2.1        seaaroundus_1.0.0 devtools_1.12.0  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7      lattice_0.20-33  digest_0.6.9     withr_1.0.2  
 [5] grid_3.3.1       R6_2.1.2         plyr_1.8.4       gtable_0.2.0  
 [9] scales_0.4.0     ggplot2_2.1.0    curl_0.9.7       sp_1.2-3  
[13] rgdal_1.1-10     tools_3.3.1      munsell_0.4.3    maps_3.1.1  
[17] colorspace_1.2-6 memoise_1.0.0    knitr_1.14

Any help or pointer much appreciated,

cheers,

François

**Comment by EvilScott** [comment]
Have you verified that `cells` is not an empty list?

**Comment by fguilhaumon** [comment]
Hi EvilScott,

thanks for looking around. Yes I verified that the "cells" vector was not empty :

`> cells[1:10]`
`[1]  88091  88092  88093  88094  88095  88096  88097  88098  88099  88100`

then sing the "getcelldata" function :

`> getcelldata(2000,cells[1:10])`
`No encoding supplied: defaulting to UTF-8.
data frame with 0 columns and 0 rows`

In fact I'm just running the examples provided in the R help files.

This problem has been reported to me by a colleague and I was able to reproduce it on several different computers.

Cheers,

F.

**Comment by EvilScott** [comment]
Hrm, not really sure what's going on here. The Sea Around Us API must have undergone an update. @LinhTran want to weigh in here?

**Comment by LinhTran** [comment]
Found a grant issue for the cell catch tables. I have applied the changes to the prod web db, so please try to access the api above again.

**Comment by fguilhaumon** [comment]
Hi !

It works perfectly. Thanks for the support.

Cheers,

François

**Comment by jafflerbach** [comment]
It seems like this error is occurring again. I'm getting the same error 

`No encoding supplied: defaulting to UTF-8. data frame with 0 columns and 0 rows` 

after running the example from `getcelldata` and it looks like others are as well, see recent comment in #7.

It seems like the error pops up [when `fromJSON` is called](https://github.com/SeaAroundUs/rseaaroundus/blob/master/R/helpers.R#L18).

**Comment by EvilScott** [comment]
@LinhTran is it possible the recent release affected this?

**Comment by oharac** [comment]
following up on this issue... I am having the same issue (zero-length dataframe result) that @jafflerbach and the original poster reported.  I tried it using the sample code and also using a vector of cells obtained using the `getcells()` function for British Columbia's EEZ.

**Comment by ableitner** [comment]
I am also getting a zero-length dataframe result using the sample code, but a different error than @jafflerbach and @fguilhaumon reported:

> getcelldata(2005, c(89568,90288,89569))
data frame with 0 columns and 0 rows
Warning message:
In charToRaw(enc2utf8(val)) :
  argument should be a character vector of length 1
all but the first element will be ignored

The same error shows up no matter what arguments I give the function. getcells() works with no issues.
Any help or suggestions with this error would be greatly appreciated.

**Comment by EvilScott** [comment]
@LinhTran can you verify tables have the appropriate grants? we need some automation to ensure that the right series of events take place on release so this data is still available (takes place on last thread too)

**Comment by LinhTran** [comment]
So i got the cell_catch data pushed to prod and grants executed. But the api call above is still not returning data.

**Comment by EvilScott** [comment]
Sounds like this may be some kind of R error with char encoding then. Any ideas @sckott ?

**Comment by sckott** [comment]
will have a look 👀

**Comment by sckott** [comment]
@ableitner what version of R and `seaaroundus` R pkg are you using?

**Comment by ableitner** [comment]
@sckott I am using R 3.2.2 GUI 1.66 Mavericks build (6996) and I just downloaded the newest seaaroundus package and citation("seaaroundus") returns Scott Chamberlain and Robert Scott Reis (). seaaroundus: Sea Around Us API Wrapper. R package version 1.0.0.

**Comment by sckott** [comment]
@ableitner I'd recommend upgrading your R version to latest (3.4)  to avoid any problems  - unless good reason to stick with older ver

Made some changes, reinstall like `devtools::install_github("ropensci/seaaroundus")` - try again , let me know if it works well for you now

**Comment by ableitner** [comment]
Great! Works now with the example code. Thank you!

**Comment by sckott** [comment]
done, via help in https://github.com/SeaAroundUs/sau-web-mt/issues/9

**Comment by theAbby** [comment]
Hi. 
I'm having this thread issue now: using R (3.4)- latest version
* able to getcells() no problem, lots of ways
* getcelldata() returning data frame with 0 columns and 0 rows, in many instances
-no warning nor error thrown.

Help most appreciated.

**Comment by theAbby** [comment]
Also, 'SeaAroundUs/sau-web-mt#9' link not work

**Comment by sckott** [comment]
that link works for me, goes to https://github.com/SeaAroundUs/sau-web-mt/issues/9

will look into `getcelldata`

**Comment by theAbby** [comment]
Thank you for looking into that Scott.
(Still no go on that other link - only interesting in terms of whatever it's content might be for troubleshooting but yah, not in Chrome nor iexpl 
Error 404-not the site I'm lookin for)

**Comment by theAbby** [comment]
https://github.com/ropensci/seaaroundus/sau-web-mt#9 says issue title is private and pops up a 404 error. If it is possible that the solution to my issue with getcalldata might be written there, can you share content?

Thank you .

**Comment by sckott** [comment]
sorry about the delay. 

that link doesn't include any R stuff, i'll try to help though. 

You didn't show examples. Can you show examples of code that you tired that doesn't work, and paste in the output of your `sessionInfo()` so I can see what version of packages yo have
